import React from "react";
import Head from "next/head";

export const CustomHead = () => {
    return(
        <Head>
            <title>Create Next App3213</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}